# Generated by Django 3.0.8 on 2020-07-12 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sequence', models.IntegerField()),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atest_app.OtherModel')),
            ],
            options={
                'unique_together': {('other', 'sequence')},
            },
        ),
    ]
