# Generated by Django 3.0.8 on 2020-07-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amodela',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='atest_app.OtherModel'),
        ),
    ]
