# Generated by Django 3.0.8 on 2020-07-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atest_app', '0002_auto_20200712_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atest_app.OtherModel')),
            ],
        ),
    ]
